### ISSUE TITLE
runserver fails

### ISSUE THREAD

**Issue by MCGallaspy** [freakboy3742/toga_web_demo#1]
Hi @freakboy3742, really great talk! I'm just trying to run your example, but I'm getting the following error:

`python manage.py runserver`:

```
Performing system checks...

Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x03A72618>
Traceback (most recent call last):
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\core\management\commands\runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\core\management\base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\core\checks\registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\core\checks\urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\core\checks\urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\core\urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Mike\toga\togapy3\lib\site-packages\django\core\urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "C:\Users\Mike\toga\togapy3\lib\importlib\__init__.py", line 109, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 2254, in _gcd_import
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1200, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1129, in _exec
  File "<frozen importlib._bootstrap>", line 1471, in exec_module
  File "<frozen importlib._bootstrap>", line 321, in _call_with_frames_removed
  File "C:\Users\Mike\toga\toga_web_demo\web_demo\urls.py", line 20, in <module>
    from example import Example
  File "C:\Users\Mike\toga\toga_web_demo\example.py", line 1, in <module>
    import toga
  File "c:\users\mike\toga\togapy3\src\toga-colosseum\toga\__init__.py", line 79, in <module>
    set_platform()
  File "c:\users\mike\toga\togapy3\src\toga-colosseum\toga\__init__.py", line 71, in set_platform
    for symbol in locals['platform'].__all__
AttributeError: 'module' object has no attribute '__all__'
```

The runserver process does not exit after this, it simply hangs until I kill it.

I'm using Windows 10 (forgive me), python 3.4.3, and all I've done prior to this is `pip install -r requirements.txt`. I see that "Windows support is minimal" for toga right now.

**Comment by MCGallaspy** [comment]
Hmm, okay, I see that the problem is with toga-win32: https://github.com/pybee/toga-win32

**Comment by freakboy3742** [comment]
Hi @MCGallaspy - Windows support *is* minimal for Toga, but thats only refers to the native widgets; Toga Web should be reasonably cross platform. You shouldn't need toga-win32 to be installed - that's the native widget part - so if it's been installed, it's a bug in the requirements handling. If you're at DjangoCon Europe, come grab me and I'll help fix it; if you're staying for the sprints cleaning up this would be a really helpful contribution.

**Comment by MCGallaspy** [comment]
>  If you're at DjangoCon Europe, come grab me and I'll help fix it;

Okay, I'm sitting in the corner at the top-level working on this right now. I'm wearing the goofy blue beach-themed hat, sans mustache. I am staying for the sprints, so at the latest I'll track you down then.

**Comment by MCGallaspy** [comment]
> You shouldn't need toga-win32 to be installed - that's the native widget part - so if it's been installed, it's a bug in the requirements handling.

What do I need then? I've determined the cause of the above error but I'm not sure what the resolution should be. [This LOC](https://github.com/freakboy3742/toga_web_demo/blob/master/manage.py#L7):

    os.environ.setdefault("TOGA_PLATFORM", "django")

Results in the `django` module being imported in [toga.set_platform](https://github.com/pybee/toga/blob/master/toga/__init__.py#L71), and when it reaches this LOC the above error occurs:

    for symbol in locals['platform'].__all__

As it says there's no `__all__` attribute. Avoiding this (i.e. with `for symbol in dir(foo)`) causes a different error. It seems that `toga-win32` and friends provide the `toga.App` attribute, but of course `django` has no `App` attribute to be imported either so I get the following traceback:

```
Unhandled exception in thread started by <pydev_monkey._NewThreadStartupWithTrace object at 0x042EF1B0>
Traceback (most recent call last):
  File "C:\Program Files (x86)\JetBrains\PyCharm 4.5.4\helpers\pydev\pydev_monkey.py", line 427, in __call__
    return self.original_func(*self.args, **self.kwargs)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\utils\autoreload.py", line 226, in wrapper
    fn(*args, **kwargs)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\core\management\commands\runserver.py", line 116, in inner_run
    self.check(display_num_errors=True)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\core\management\base.py", line 426, in check
    include_deployment_checks=include_deployment_checks,
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\core\checks\registry.py", line 75, in run_checks
    new_errors = check(app_configs=app_configs)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\core\checks\urls.py", line 10, in check_url_config
    return check_resolver(resolver)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\core\checks\urls.py", line 19, in check_resolver
    for pattern in resolver.url_patterns:
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\core\urlresolvers.py", line 417, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\utils\functional.py", line 33, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "D:\toga_stuff\web-demo-env\lib\site-packages\django\core\urlresolvers.py", line 410, in urlconf_module
    return import_module(self.urlconf_name)
  File "D:\toga_stuff\web-demo-env\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 986, in _gcd_import
  File "<frozen importlib._bootstrap>", line 969, in _find_and_load
  File "<frozen importlib._bootstrap>", line 958, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 673, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 662, in exec_module
  File "<frozen importlib._bootstrap>", line 222, in _call_with_frames_removed
  File "D:\toga_stuff\toga_web_demo\web_demo\urls.py", line 20, in <module>
    from example import Example
  File "D:\toga_stuff\toga_web_demo\example.py", line 4, in <module>
    class Example(toga.App):
AttributeError: module 'django' has no attribute 'App'
```

I'm a bit stumped now. (FWIW I upgraded to python 3.5.1.)
